import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';

import Navbar from '@/components/navbar';
import ToastProvider from '@/providers/toast-provider';
import ScrollToTopArrow from '@/components/scroll-to-top-arrow';

import './globals.css';
import Footer from '@/components/footer';

const font = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode;
	params: { locale: string };
}) {
	return (
		<html lang="en">
			<body className={font.className}>
				<ToastProvider />
				<Navbar />
				{children}
				<Footer />
				<ScrollToTopArrow />
			</body>
		</html>
	);
}
